steps:
  # 1. Docker 이미지 빌드
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "asia-northeast3-docker.pkg.dev/sound-jigsaw-459108-s9/tina-app-images/tina-galxe-api-${_ENVIRONMENT}"
      - "."

  # 2. Artifact Registry에 푸시
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "asia-northeast3-docker.pkg.dev/sound-jigsaw-459108-s9/tina-app-images/tina-galxe-api-${_ENVIRONMENT}"

  # 3. Cloud Run 배포
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "tina-galxe-api-${_ENVIRONMENT}"
      - "--image"
      - "asia-northeast3-docker.pkg.dev/sound-jigsaw-459108-s9/tina-app-images/tina-galxe-api-${_ENVIRONMENT}"
      - "--region"
      - "asia-northeast3"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--set-env-vars"
      - "NODE_ENV=${_ENVIRONMENT}"

images:
  - "asia-northeast3-docker.pkg.dev/sound-jigsaw-459108-s9/tina-app-images/tina-galxe-api-${_ENVIRONMENT}"

substitutions:
  _ENVIRONMENT: "dev"
